before_script:
  - ./docker-build.sh

stages:
  - build
  - deploy

buildDevBranches:
  stage: build
  script:
    - ./prod-build.sh
  except:
    - master

deployToProduction:
  stage: deploy
  script:
    - ./prod-build.sh
    - ./prod-deploy.sh
  only:
    - master
