before_script:
  - ./docker-build.sh

stages:
  - build
  - deploy

buildDevBranches:
  stage: build
  script:
    - ./build.sh
  except:
    - master

deployToProduction:
  stage: deploy
  script:
    - ./build.sh
    - ./deploy.sh
  only:
    - master