sudo: required

language: bash

services:
  - docker

before_script:
  - docker-compose -v

script:
  - docker-compose build
  - docker-compose run --rm jekyll
  - docker-compose run --rm node

deploy:
  provider: script
  script: ./deploy.sh
  on:
    branch: master
  skip_cleanup: true

cache:
  directories:
    - bower_components
    - node_modules
