
title: WebElement
email: kontakt@webelement.sk

description: "Stretnutie web developerov v Bratislave a Pre코ove, predn치코ky, prezent치cie"
baseurl: ""
url: "http://webelement.sk"

links:
  github: '<a href="https://github.com/webelement">Github</a>'
  twitter: '<a href="https://twitter.com/webelement">Twitter</a>'
  facebook: '<a href="https://facebook.com/groups/webelement">Facebook</a>'
  youtube: '<a href="https://www.youtube.com/channel/UC7ytCGu5KVT7yq5tSMSqHow">Youtube</a>'
  flickr: '<a href="https://www.flickr.com/groups/webelement">Flickr</a>'
  meetup: '<a href="http://meetup.com/webelement/">Meetup</a>'

timezone: "Europe/Bratislava"

markdown: kramdown
permalink: /event/:title/
exclude:
  - bower.json
  - README.md
  - Dockerfile
  - CNAME
  - LICENSE
  - twitter-secrets.php
  - speakers.php
  - vendor/symfony
  - vendor/dg
  - vendor/composer
  - docker-run.sh
  - docker-build.sh
  - composer.json
  - composer.lock

gems:
  - jekyll-sitemap
  - jekyll-redirect-from
