
title: WebElement
email: kontakt@webelement.sk

description: "Stretnutie web developerov v Bratislave a Pre코ove, predn치코ky, prezent치cie"
baseurl: ""
url: "https://webelement.sk"

anchors:
  github: '<a href="https://github.com/webelement" target="_blank">Github</a>'
  twitter: '<a href="https://twitter.com/webelement" target="_blank">Twitter</a>'
  facebook: '<a href="https://facebook.com/groups/webelement" target="_blank">Facebook</a>'
  youtube: '<a href="https://www.youtube.com/channel/UC7ytCGu5KVT7yq5tSMSqHow" target="_blank">Youtube</a>'
  flickr: '<a href="https://www.flickr.com/groups/webelement" target="_blank">Flickr</a>'
  meetup: '<a href="http://meetup.com/webelement" target="_blank">Meetup</a>'
  gitter: '<a href="https://gitter.im/webelement/chat" target="_blank">Gitter</a>'

links:
  twitter: https://twitter.com/webelement
  github: https://github.com/webelement
  facebook: https://facebook.com/groups/webelement
  youtube: https://www.youtube.com/channel/UC7ytCGu5KVT7yq5tSMSqHow
  flickr: https://www.flickr.com/groups/webelement
  meetup: http://meetup.com/webelement
  gitter: https://gitter.im/webelement/chat

timezone: "Europe/Bratislava"

markdown: kramdown
permalink: /event/:title/
exclude:
  - bower.json
  - README.md
  - CNAME
  - LICENSE
  - twitter-secrets.php
  - speakers.php
  - vendor
  - fontello
  - Dockerfile
  - docker-run.sh
  - docker-build.sh
  - composer.json
  - composer.lock
  - node_modules
  - gulpfile.js
  - package.json
  - css/main.less
  - images/speakers/sprite/sprite.css
  - _build
  - bower_components
  - build.sh
  - deploy.sh

gems:
  - jekyll-sitemap
  - jekyll-redirect-from
